arecord eliminated

diff --git a/bash/speech2text b/bash/speech2text
--- a/bash/speech2text
+++ b/bash/speech2text
@@ -7,9 +7,8 @@
 # 
  
 # Poderíamos testar com:
-# [ "$(whereis arecord | cut -d: -f2)" == "" ] { echo "can't find arecord"; exit; }
+# [ "$(whereis ffmpeg | cut -d: -f2)" == "" ] { echo "can't find arecord"; exit; }
 
-[ -x /usr/bin/arecord ] || ( echo "can't find arecord"; exit; }
 [ -x /usr/bin/wget ]    || ( echo "cant't find wget"; exit; )
 [ -x /usr/bin/ffmpeg ]  || ( echo "can't find ffmpeg"; exit; )
 [ -x /usr/bin/lynx ]    || ( echo "can't find lynx"; exit; )
@@ -23,18 +22,18 @@ say() {
   mplayer -ao alsa -really-quiet -noconsolecontrols "http://translate.google.com/translate_tts?ie=UTF-8&tl=${TO_LANG}&q=$*" 2> /dev/null; 
 }
 
-TMP_WAV="$(mktemp /tmp/tmp_XXXXXXXXXXXX.wav)"
 TMP_FLAC="$(mktemp /tmp/tmp_XXXXXXXXXXXX.flac)"
+
+trap "" INT
 
 echo "Recording... Press Ctrl+C to Stop."
 
-arecord -f SE16_LE -c 1 -r 22050 -t wav $TMP_WAV
-ffmpeg -loglevel panic -y -i $TMP_WAV -ar 16000 -acodec flac $TMP_FLAC  > /dev/null 2>&1
+ffmpeg -f alsa -i hw:0 -ar 16000 -ac 1 -acodec flac "$TMP_FLAC" > /dev/null 2>&1
 
 echo "Processing..."
 
 wget -q -U "Mozilla/5.0" \
-     --post-file $TMP_FLAC \
+     --post-file "$TMP_FLAC" \
      --header "Content-Type: audio/x-flac; rate=16000" \
       -O - "http://www.google.com/speech-api/v1/recognize?lang=${FROM_LANG2}&client=chromium" | \
         cut -d\" -f12  > stt.txt
@@ -50,5 +49,5 @@ en_string=`lynx -source "http://translate.google.com?tr=${FROM_LANG}&hl=${TO_LAN
 
 say $en_string
 
-rm -f $TMP_WAV $TMP_FLAC > /dev/null 2>&1
+#rm -f $TMP_FLAC
 
