Modified scripts

diff --git a/bash/vid2mp4 b/bash/vid2mp4
--- a/bash/vid2mp4
+++ b/bash/vid2mp4
@@ -1,75 +1,51 @@
 #!/bin/bash
 
 [[ $# -lt 1 ]] && { 
-	echo "Usage: vid2mp4 [--copy] <inputvideo>"; 
+	echo "Usage: vid2mp4 <inputvideo>"; 
 	exit 3; 
 }
 
-COPY=0
-if [ "$1" == "--copy" ]; then
-  COPY=1
-  FILE="$2"
-else
-  if [ "$2" == "--copy" ]; then
-    COPY=1
-  fi
-  FILE="$1"
-fi
+FILENAME="$1"
 
 EXTRA_PARAMS="-map_metadata -1" # Retira metadados do vídeo destino.
 
-VCODEC=`ffprobe "$FILE" 2>&1 | grep Video: | sed 's/^.*Video: \(\w*\) .*$/\1/'`
+VCODEC=`ffprobe "$1" 2>&1 | sed -n '/Video:/s/^.\+Video: \(\w\+\),* \+.\+$/\1/p'`
+
+# Usa preset do x264 com maior poder de análise.
 if [ "$VCODEC" == "h264" ]; then
   VPARAMS="-c:v copy"
 else
-  # Usa preset do x264 com maior poder de análise.
   VPARAMS="-c:v libx264 -q:v 0"
 fi
 
-ACODEC=`ffprobe "$FILE" 2>&1 | grep Audio: | sed 's/^.*Audio: \(\w*\) .*$/\1/'`
+ACODEC="$(ffprobe "$FILENAME" 2>&1 | sed -n '/Audio:/s/^.\+Audio: \(\w\+\),* \+.\+$/\1/p')"
+
 if [ "$ACODEC" == "ac3" ]; then
   APARAMS="-c:a copy"
 else
-  ABR=$(ffmpeg -i "$FILE" 2>&1 | grep Audio: | sed 's/^.*, \([0-9]*\) kb\/s.*$/\1/');
+  ABR="$(ffprobe "$FILENAME" 2>&1 | sed -n '/Audio:/s/^.\+ \([0-9]\+\) kb\/s.\+$/\1/p')"
+  if [ "$ABR" == "" ]; then 
+    echo "Cannot find \"${FILENAME}\"."
+    exit 3 
+  fi
+
   if [ $ABR -le 64 ]; then ABR=64; else
-    if [ $ABR -le 96 ]; then ABR=96; else
-      if [ $ABR -le 128 ]; then ABR=128; else
-        if [ $ABR -le 160 ]; then ABR=160; else
-          ABR=192;
+    if [ $ABR -lt 96 ]; then ABR=64; else
+      if [ $ABR -lt 128 ]; then ABR=96; else
+        if [ $ABR -lt 160 ]; then ABR=128; else
+          if [ $ABR -lt 192 ]; then ABR=160; else
+            ABR=192;
+          fi
         fi 
       fi 
     fi 
   fi
 
-  # Convert to stereo!
   APARAMS="-c:a ac3 -b:a ${ABR}k -ac 2"
-
-  unset ABR
 fi
 
 TMPFNAME="$(mktemp /tmp/tmp_XXXXXXXXXX.mp4)"
-OFNAME="${FILE%.*}.mp4"
+OFNAME="${FILENAME%.*}.mp4"
 
-# If we want to make a copy, check if the output filename is the same as the input...
-if [ $COPY -eq 1 ]; then
-  if [ "$OFNAME" == "$FILE" ]; then
-    OFNAME="_$OFNAME"
-  fi
-fi
-
-ffmpeg -y -i "$FILE" $VPARAMS $APARAMS $EXTRA_PARAMS "$TMPFNAME"
-if [ $? -eq 0 ]; then 
-  # If we want to overwrite, delete the original file...
-  if [ $COPY -eq 0 ]; then
-    rm "$FILE"
-  fi
-
-  # ... move the temporary file to the new one.
-  mv "$TMPFNAME" "$OFNAME"
-else
-  # in case of error, delete the temporary.
-  rm "$TMPFNAME"
-fi
-
-unset VPARAMS APARAMS EXTRA_PARAMS TMPFNAME OFNAME
+ffmpeg -y -i "$FILENAME" $VPARAMS $APARAMS $EXTRA_PARAMS $TMPFNAME && rm "$FILENAME" && mv $TMPFNAME "$OFNAME"
 
